Use shellcheck-approved bash script for copyright workflow
Signed-off-by: Antonia Gaete <agaete@linuxfoundation.org>

diff --git a/.github/workflows/license-header-check.yml b/.github/workflows/license-header-check.yml
--- a/.github/workflows/license-header-check.yml
+++ b/.github/workflows/license-header-check.yml
@@ -13,37 +13,15 @@ on:
         type: string
         default: "Copyright The Linux Foundation"
       include_files:
-        description: "JSON array of file patterns to include"
+        description: "A comma-separated list of additional file patterns to include"
         required: false
         type: string
-        default: |
-          [
-            "*.go",
-            "go.mod",
-            "*.py",
-            "*.html",
-            "*.css",
-            "*.ts",
-            "*.js",
-            "*.scss",
-            "*.sh",
-            "*.bash",
-            "*.ksh",
-            "*.csh",
-            "*.tcsh",
-            "*.fsh",
-            "Makefile",
-            "*.txt",
-            "*.yaml",
-            "*.yml",
-            ".gitignore",
-            "*.sql"
-          ]
+        default: ""
       exclude_pattern:
-        description: "Regex pattern for files to exclude"
+        description: "A comma-separated list of additional patterns to exclude"
         required: false
         type: string
-        default: "node_modules|.venv|organization-service.yaml|project-service.yaml|acs-service.yaml|user-service.yaml|api.*.compiled.yaml|.vendor-new|.pytest_cache|.idea"
+        default: ""
 
 permissions:
   contents: read
@@ -66,27 +44,55 @@ jobs:
           # Exits with a 0 if all source files have license headers
           # Exits with a 1 if one or more source files are missing a license header
 
-          # These are the file patterns we should exclude - these are typically transient files not checked into source control
-          exclude_pattern='${{ inputs.exclude_pattern }}'
+          # Exclude code coming from a third-party. Typically these won't be checked into
+          # source control, but occasionally "vendored" code is committed.
+          exclude_pattern='^(.*/)?(node_modules|vendor)/'
 
-          # These are the file patterns we should include
-          # Adjust these filters based on the source files you are interested in checking
-          include_files=($(echo '${{ inputs.include_files }}' | jq -r '.[]'))
+          # Include build definitions.
+          filetypes=(Makefile Dockerfile .gitignore .dockerignore)
+          # Include Golang files.
+          filetypes+=("*.go" go.mod)
+          # Include Python files.
+          filetypes+=("*.py")
+          # Include HTML, CSS, JS, TS, SCSS.
+          filetypes+=("*.html" "*.htm" "*.css" "*.ts" "*.js" "*.scss")
+          # Include shell scripts.
+          filetypes+=("*.sh" "*.bash" "*.ksh" "*.csh" "*.tcsh" "*.fsh")
+          # Include text.
+          filetypes+=("*.txt")
+          # Include YAML and TOML files.
+          filetypes+=("*.yaml" "*.yml" "*.toml")
+          # Include SQL scripts and definitions.
+          filetypes+=("*.sql")
 
-          # Compile those into a formatted string to pass into find command
-          include_pattern=""
-          for file in "${include_files[@]}"; do
-              # if include_pattern is not empty, add ` -o`, otherwise add nothing
-              include_pattern+="${include_pattern:+ -o }-name '${file}'"
-          done
+          # Add any files types included in the input
+          if [[ -n "${{ inputs.include_files }}" ]]; then
+            IFS=',' read -ra additional_files <<< "${{ inputs.include_files }}"
+            for file in "${additional_files[@]}"; do
+                filetypes+=("${file}")
+            done
+          fi
+
+          # Build regex pattern with any `exclude_pattern` input values
+          if [[ -n "${{ inputs.exclude_pattern }}" ]]; then
+            exclude_pattern='^(.*/)?(node_modules|vendor' # unclosed regex so we can append the user's input
+
+            IFS=',' read -ra additional_excludes <<< "${{ inputs.exclude_pattern }}"
+
+            for pattern in "${additional_excludes[@]}"; do
+              exclude_pattern="${exclude_pattern}|${pattern}"
+            done
+
+            exclude_pattern="${exclude_pattern})/"
+          else
+            exclude_pattern='^(.*/)?(node_modules|vendor)/'
+          fi
 
           files=()
-          echo "Scanning source code..."
-          # Loads all the filenames into an array
-          files=($(eval "find . -type f \( ${include_pattern} \) -print" | egrep -v "${exclude_pattern}"))
+          while IFS='' read -r line; do files+=("$line"); done < <(git ls-files -c "${filetypes[@]}" | grep -E -v "${exclude_pattern}")
 
           # This is the copyright line to look for - adjust as necessary
-          copyright_line="${{ inputs.copyright_line }}"
+          copyright_line="Copyright The Linux Foundation"
 
           # Flag to indicate if we were successful or not
           missing_license_header=0
@@ -94,24 +100,24 @@ jobs:
           # For each file...
           echo "Checking ${#files[@]} source code files for the license header..."
           for file in "${files[@]}"; do
-            # echo "Processing file ${file}..."
+           	# echo "Processing file ${file}..."
 
-            # Header is typically one of the first few lines in the file...
-            head -4 "${file}" | grep -q "${copyright_line}"
-            # Find it? exit code value of 0 indicates the grep found a match
-            exit_code=$?
-            if [[ ${exit_code} -ne 0 ]]; then
-              echo "${file} is missing the license header"
-              # update our flag - we'll fail the test
-              missing_license_header=1
+           	# Header is typically one of the first few lines in the file...
+           	head -4 "${file}" | grep -q "${copyright_line}"
+           	# Find it? exit code value of 0 indicates the grep found a match
+           	exit_code=$?
+           	if [[ ${exit_code} -ne 0 ]]; then
+          		echo "${file} is missing the license header"
+          		# update our flag - we'll fail the test
+          		missing_license_header=1
             fi
           done
 
           # Summary
           if [[ ${missing_license_header} -eq 1 ]]; then
-            echo "One or more source files is missing the license header."
+         	  echo "One or more source files is missing the license header."
           else
-            echo "License check passed."
+         	  echo "License check passed."
           fi
 
           # Exit with status code 0 = success, 1 = failed
