Fix formatting
Signed-off-by: Antonia Gaete <agaete@linuxfoundation.org>

diff --git a/.github/workflows/license-header-check.yml b/.github/workflows/license-header-check.yml
--- a/.github/workflows/license-header-check.yml
+++ b/.github/workflows/license-header-check.yml
@@ -92,7 +92,7 @@ jobs:
           while IFS='' read -r line; do files+=("$line"); done < <(git ls-files -c "${filetypes[@]}" | grep -E -v "${exclude_pattern}")
 
           # This is the copyright line to look for - adjust as necessary
-          copyright_line="Copyright The Linux Foundation"
+          copyright_line="${{ inputs.copyright_line }}"
 
           # Flag to indicate if we were successful or not
           missing_license_header=0
@@ -100,24 +100,24 @@ jobs:
           # For each file...
           echo "Checking ${#files[@]} source code files for the license header..."
           for file in "${files[@]}"; do
-           	# echo "Processing file ${file}..."
+            # echo "Processing file ${file}..."
 
-           	# Header is typically one of the first few lines in the file...
-           	head -4 "${file}" | grep -q "${copyright_line}"
-           	# Find it? exit code value of 0 indicates the grep found a match
-           	exit_code=$?
-           	if [[ ${exit_code} -ne 0 ]]; then
-          		echo "${file} is missing the license header"
-          		# update our flag - we'll fail the test
-          		missing_license_header=1
+            # Header is typically one of the first few lines in the file...
+            head -4 "${file}" | grep -q "${copyright_line}"
+            # Find it? exit code value of 0 indicates the grep found a match
+            exit_code=$?
+            if [[ ${exit_code} -ne 0 ]]; then
+              echo "${file} is missing the license header"
+              # update our flag - we'll fail the test
+              missing_license_header=1
             fi
           done
 
           # Summary
           if [[ ${missing_license_header} -eq 1 ]]; then
-         	  echo "One or more source files is missing the license header."
+            echo "One or more source files is missing the license header."
           else
-         	  echo "License check passed."
+            echo "License check passed."
           fi
 
           # Exit with status code 0 = success, 1 = failed
